version: "2"
services:
  node:
    build: ./
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "8000:8000"
    command: "npm run start"
